[package]
name = "devmem"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
name = "devmem"
path = "src/lib.rs"

[[bin]]
name = "devmem"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
libc = "0.2"
thiserror = "1.0"

[dev-dependencies]
